name: Zone2
version: ${project.version}
main: io.github.itscryne.zone2.Zone2
api-version: 1.13
commands:
  createPlayerZone:
    usage: /createPlayerZone
  getPlayerZone:
    usage: /getPlayerZone
  deletePlayerZone:
    usage: /deletPlayerZone

  createServerZone:
    usage: /createServerZone
  getServerZone:
    usage: /getServerZone
  deleteServerZone:
    usage: /deleteServerZone
