name: Zone2
version: ${project.version}
main: io.github.itscryne.zone2.Zone2
api-version: 1.13
commands:
  createzone:
    usage: /createzone <hx lx hz lz>
  createserverzone:
    usage: /createserverzone <hx lx hy ly hz lz world priority name>
